import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Air Conditioner',
      slug: 'air-conditioner',
      category: 'Industrial Equipment',
      image: '/images/airconditioner.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 1000,
      brand: 'CAT',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Air Conditioner',
    },
    {
      name: 'Heavy Equipment',
      slug: 'heavy-equipment',
      category: 'Industrial Equipment',
      image: '/images/cat.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1000,
      brand: 'JCB',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Heavy Equipment',
    },
    {
      name: 'Generator',
      slug: 'generator',
      category: 'Industrial Equipment',
      image: '/images/generator.jpg',
      price: 1000,
      brand: 'Doosan',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Generator',
    },
    {
      name: 'Gas Turbines',
      slug: 'gas turbines',
      category: 'Oil and Gas',
      image: '/images/oilgas.jpg',
      price: 1000,
      brand: 'Hitachi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Gas Turbines',
    },
    {
      name: 'Well Head',
      slug: 'well-head',
      category: 'Oil and Gas',
      image: '/images/oilgas2.jpg',
      price: 1000,
      brand: 'Sany',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Well Head',
    },
    {
      name: 'Tractor',
      slug: 'tractor',
      category: 'Oil and Gas',
      image: '/images/cat.jpg',
      price: 1000,
      brand: 'Volvo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tractor',
    },
  ],
};
export default data;
